#!/bin/bash

CONFIG_PATH="${HOME}/.config/cursor"

CURSOR_API_KEY=$(cat "${CONFIG_PATH}/token")

docker run --rm --env CURSOR_API_KEY=$CURSOR_API_KEY --volume .:/home/ubuntu/app -it cursor:latest "$@"
